#!/usr/bin/env bash
# transfers a file from our client to a server


sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" > index.html
sudo mv index.html /var/www/html

sed -i 's/root \/var\/www\/html;/root \/var\/www\/html;\n\trewrite ^\/redirect_me http:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sudo service nginx restart
