#!/usr/bin/env bash
# configure web-02 to be identical to web-01

apt-get -y update
apt-get -y install nginx
sed -i "/server_name _;/ a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
service nginx start
