#!/usr/bin/env bash
# Script to install and configure HAProxy 1.6.
apt-get -y update
apt-get install -y haproxy=1.6.*
echo -e "frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend 01_backend\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend 01_backend\n\tbalance roundrobin\n\tserver 2309-web-01 35.231.233.84:80 check\n\tserver 2309-web-02 34.207.112.220:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
